//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeListenPlayer.AmazonHandler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class AmazonUserCredentials : global::System.Configuration.ApplicationSettingsBase {
        
        private static AmazonUserCredentials defaultInstance = ((AmazonUserCredentials)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AmazonUserCredentials())));
        
        public static AmazonUserCredentials Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AKIAJUB3ZROHGM2ISRGA")]
        public string Key {
            get {
                return ((string)(this["Key"]));
            }
            set {
                this["Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4tSUnZMiS7dkG65nHBFhJmRRuVJy8m1Vg4Jbvb+1 ")]
        public string Secret {
            get {
                return ((string)(this["Secret"]));
            }
            set {
                this["Secret"] = value;
            }
        }
    }
}
