//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeListenPlayer1._1_WPF.LastFmHandler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LastFmUserCredentials : global::System.Configuration.ApplicationSettingsBase {
        
        private static LastFmUserCredentials defaultInstance = ((LastFmUserCredentials)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LastFmUserCredentials())));
        
        public static LastFmUserCredentials Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69473ce24376ae029d0b35211016700c")]
        public string Key {
            get {
                return ((string)(this["Key"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("305fef5dd50570f5da565ffb863a65ef")]
        public string Secret {
            get {
                return ((string)(this["Secret"]));
            }
        }
    }
}
